[CmdletBinding()]
param(
  [string]$Operator = $env:USERNAME,
  [string]$WindowsProfile = $env:USERPROFILE,
  [string]$OutputPath = "release/manual-release-gates.json",
  [string[]]$InstallerArtifacts = @(
    "src-tauri/target/release/bundle/nsis/Bible AI_0.1.0_x64-setup.exe",
    "src-tauri/target/release/bundle/msi/Bible AI_0.1.0_x64_en-US.msi"
  ),
  [int]$RequiredProviderCredentialCount = 2,
  [switch]$CleanProfileInstallPassed,
  [switch]$FirstLaunchPassed,
  [switch]$SettingsProviderKeysPassed,
  [switch]$CredentialVaultUpgradeProfilePassed,
  [switch]$ExportsSecretLeakCheckPassed,
  [switch]$BackupRestorePassed,
  [switch]$SqliteBackupRestorePassed,
  [switch]$KeyboardOnlyWorkflowPassed,
  [switch]$ScreenReaderSmokePassed,
  [switch]$Zoom200PercentPassed,
  [switch]$SensitiveTopicWordingReviewPassed,
  [switch]$LocalizedCrisisResourcesReviewPassed
)

$ErrorActionPreference = "Stop"

function ConvertTo-RepoPath {
  param([string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) {
    return $Path
  }
  return (Join-Path (Get-Location) $Path)
}

function Get-CredentialTargetCount {
  $providerTargets = @(
    "google_api_key.Bible AI",
    "openai_api_key.Bible AI",
    "anthropic_api_key.Bible AI",
    "managed_gateway_token.Bible AI"
  )

  $cmdkeyOutput = ""
  try {
    $cmdkeyOutput = (& cmdkey.exe /list 2>$null) -join "`n"
  } catch {
    return 0
  }

  $count = 0
  foreach ($target in $providerTargets) {
    if ($cmdkeyOutput -match [regex]::Escape($target)) {
      $count += 1
    }
  }
  return $count
}

function Get-SqliteSecretSignalCount {
  $dbPath = Join-Path $env:APPDATA "com.jm.bibleai\user.sqlite"
  if (-not (Test-Path -LiteralPath $dbPath)) {
    return $null
  }

  $bytes = [System.IO.File]::ReadAllBytes($dbPath)
  $text = [System.Text.Encoding]::UTF8.GetString($bytes)
  $patterns = @(
    "google_api_key",
    "openai_api_key",
    "anthropic_api_key",
    "managed_gateway_token",
    "sk-",
    "AIza"
  )

  $count = 0
  foreach ($pattern in $patterns) {
    if ($text.IndexOf($pattern, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
      $count += 1
    }
  }
  return $count
}

function Test-ArtifactList {
  param([string[]]$Paths)
  $missing = @()
  foreach ($path in $Paths) {
    $resolved = ConvertTo-RepoPath $path
    if (-not (Test-Path -LiteralPath $resolved)) {
      $missing += $path
    }
  }
  return $missing
}

function Get-ArtifactEvidence {
  param([string[]]$Paths)
  $items = @()
  foreach ($path in $Paths) {
    $resolved = ConvertTo-RepoPath $path
    if (-not (Test-Path -LiteralPath $resolved -PathType Leaf)) {
      continue
    }
    $file = Get-Item -LiteralPath $resolved
    $items += [ordered]@{
      name = $file.Name
      bytes = [int64]$file.Length
      sha256 = (Get-FileHash -LiteralPath $resolved -Algorithm SHA256).Hash.ToLowerInvariant()
    }
  }
  return $items
}

$credentialTargetCount = Get-CredentialTargetCount
$sqliteSecretSignalCount = Get-SqliteSecretSignalCount
$missingArtifacts = Test-ArtifactList $InstallerArtifacts
$artifactEvidence = @(Get-ArtifactEvidence $InstallerArtifacts)
$vaultCleanProfilePassed = (
  $credentialTargetCount -ge $RequiredProviderCredentialCount -and
  $null -ne $sqliteSecretSignalCount -and
  $sqliteSecretSignalCount -eq 0
)

$notes = @(
  "Generated by scripts/collect-manual-release-gates.ps1.",
  "Run from the separate clean Windows profile or VM used for manual QA.",
  "Credential values were not read, printed, or written into this evidence file.",
  "Detected $credentialTargetCount provider credential entries in Windows Credential Manager.",
  "Required provider credential entries for this gate: $RequiredProviderCredentialCount."
)

if ($null -eq $sqliteSecretSignalCount) {
  $notes += "User database was not found under this profile's roaming app data path."
} else {
  $notes += "SQLite sensitive-string signal count: $sqliteSecretSignalCount."
}

if ($missingArtifacts.Count -gt 0) {
  $notes += "Missing installer artifacts from this working directory: $($missingArtifacts -join ', ')."
}

$evidence = [ordered]@{
  operator = $Operator
  completed_at = (Get-Date).ToUniversalTime().ToString("o")
  windows_profile = $WindowsProfile
  installer_artifacts = $artifactEvidence
  clean_profile_install_passed = [bool]$CleanProfileInstallPassed
  first_launch_passed = [bool]$FirstLaunchPassed
  settings_provider_keys_passed = [bool]$SettingsProviderKeysPassed
  credential_vault_clean_profile_passed = [bool]$vaultCleanProfilePassed
  credential_vault_upgrade_profile_passed = [bool]$CredentialVaultUpgradeProfilePassed
  exports_secret_leak_check_passed = [bool]$ExportsSecretLeakCheckPassed
  backup_restore_passed = [bool]$BackupRestorePassed
  sqlite_backup_restore_passed = [bool]$SqliteBackupRestorePassed
  keyboard_only_workflow_passed = [bool]$KeyboardOnlyWorkflowPassed
  screen_reader_smoke_passed = [bool]$ScreenReaderSmokePassed
  zoom_200_percent_passed = [bool]$Zoom200PercentPassed
  sensitive_topic_wording_review_passed = [bool]$SensitiveTopicWordingReviewPassed
  localized_crisis_resources_review_passed = [bool]$LocalizedCrisisResourcesReviewPassed
  notes = $notes
}

$resolvedOutputPath = ConvertTo-RepoPath $OutputPath
$outputDirectory = Split-Path -Parent $resolvedOutputPath
if ($outputDirectory) {
  New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}

$json = $evidence | ConvertTo-Json -Depth 4
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($resolvedOutputPath, $json + [Environment]::NewLine, $utf8NoBom)
Write-Host "Wrote manual release gate evidence: $resolvedOutputPath"
Write-Host "Provider credential entries detected: $credentialTargetCount"
if ($null -eq $sqliteSecretSignalCount) {
  Write-Host "SQLite sensitive-string signal count: unavailable because user.sqlite was not found"
} else {
  Write-Host "SQLite sensitive-string signal count: $sqliteSecretSignalCount"
}
if ($vaultCleanProfilePassed) {
  Write-Host "Clean-profile credential vault check passed."
} else {
  Write-Host "Clean-profile credential vault check is incomplete."
}
